apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::652405611807:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JC2TWJDQMVL3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::652405611807:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T17:00:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1888"
  uid: 367255df-faf1-4505-977f-1238e7535d84
